@doc raw"""
    symmetric_verlinde_category(p::Integer; plus=false, skeletal=true, check=false)
    symmetric_verlinde_category(F::Field; plus=false, skeletal=true, check=false)

Construct the symmetric Verlinde category ``\operatorname{Ver}_p`` in
characteristic ``p`` as the semisimplification of
``\operatorname{Rep}_F(C_p)``. The integer method uses `GF(p)`. The field
method currently supports finite fields of positive characteristic.

Set `plus=true` to construct the fusion subcategory
``\operatorname{Ver}_p^+`` generated by ``L_3``; its simple objects have odd
labels. By default the result is a `SixJCategory` whose simple objects are
named `L1`, `L2`, and so on. Set `skeletal=false` to retain the quotient model
and its representation-theoretic objects. With `check=true`, verify the
transported skeletal structure.

This construction is distinct from the characteristic-zero quantum-group
constructor [`verlinde_category`](@ref verlinde-models).
"""
function symmetric_verlinde_category(p::Integer; plus::Bool=false,
                                     skeletal::Bool=true, check::Bool=false)
    p >= 2 && Oscar.is_prime(ZZ(p)) ||
        throw(ArgumentError("p must be prime"))
    symmetric_verlinde_category(GF(p); plus, skeletal, check)
end

function symmetric_verlinde_category(F::Field; plus::Bool=false,
                                     skeletal::Bool=true, check::Bool=false)
    p = Int(characteristic(F))
    p > 0 || throw(ArgumentError("positive characteristic is required"))
    is_finite(F) || throw(ArgumentError(
        "the representation backend currently requires a finite field"))

    R = rep(F, Oscar.cyclic_group(p))
    generator_dimension = plus ? (p <= 3 ? 1 : 3) : (p == 2 ? 1 : 2)
    jordan_block = identity_matrix(F, generator_dimension)
    for i in 1:generator_dimension-1
        jordan_block[i, i + 1] = one(F)
    end
    generator = Representation(R, gens(base_group(R)), [jordan_block])

    T = tensor_power_category(generator)
    Q = semisimplification(T)
    S = simples(Q)
    sort!(S; by=X -> int_dim(object(object(X))))
    labels = [int_dim(object(object(X))) for X in S]
    expected = plus ? collect(1:2:p-1) : collect(1:p-1)
    labels == expected || error("unexpected Jordan-block labels: $labels")
    Q.simples = S
    skeletal || return Q

    V = six_j_category(Q, S, ["L$i" for i in labels]; check)
    set_name!(V, plus ? "Symmetric Verlinde category Ver_$p^+ over $F" :
                        "Symmetric Verlinde category Ver_$p over $F")
    V
end
